### ISSUE TITLE
エッジの条件にマッチしたノードのみを取得するようにする

### ISSUE THREAD

**Issue by matsusho070** [g2gml/g2g#11]
現在のg2g mapperはエッジとノードの取得は個別に行われているが、
このままだと、例えば条件を満たすエッジとそれにまつわるノードのみを取ってくるようなG2GMLが書きづらい。むしろエッジの条件にマッチしたノードのみを取得するようにする動作を基本として、マッチしていないノードも含めて取得するような動作はオプションとして指定できるような形にすると使いやすいのではないか

**Comment by ryotayamanaka** [comment]
現状の実装は、
ノードの制約はエッジの検索に引き継がれるが、
エッジの制約はノードの検索に引き継がれない

例として、
A から始まるミュージシャンを取ってこれても、
A から始まるグループ（エッジ・プロパティに押し込まれる）
で繋がったミュージシャンを取ってこれない

そこで、エッジの制約をノードの検索引き継ぐと、
その制約を満たすエッジを持たないノードは取得されなくなる

しかし、これは生成後のグラフで Orphan ノードなので、
取ってこれなくてもよいのではないか

ノードとエッジを別々の SPARQL で取ってくるところは、
今後も変わらないですよね？

**Comment by matsusho070** [comment]
確かに別々のSPARQLのままでも取れましたね・・・
一方で、あるエッジに関するSPARQLがノードも一緒に取ってくるようになると
1. SPARQLの発行が1回ですむためJenaを使う場合はデータのロードが減ってちょっと早くなる
2. エッジに関してLIMITをかけた検索を実装しやすくなる
というメリットもあるような気がしてきました

**Comment by ryotayamanaka** [comment]
先程の議論の結果：

- エッジ定義の条件をノード取得時の SPARQL に反映させる
- 変更後、Orphan ノードが取得されなくなる（取得するオプションもおいおい検討）
- ノードごと、エッジごと、に SPARQL を発行する内部動作は変更しない
- G2GML のシンタックスや書き方は変更しない
- エッジ（及びノード）に対する LIMIT の実装については今回は見送る

**Comment by ryotayamanaka** [comment]
0.2.0 で対応完了

**Comment by ryotayamanaka** [comment]
0.2.0 で対応完了
