### ISSUE TITLE
g2g docker file is based on old version 0.3.4

### ISSUE THREAD

**Issue by misqe** [g2gml/g2g#19]
Hi, 
was just wondering if there is a reason why the g2g docker file has not been updated to be based on latest 0.3.5 version of pg docker image and is still pointing to 0.3.4?
https://github.com/g2glab/g2g/blob/master/Dockerfile#L1

The reason I am asking is that I am looking at OWL/RDF to PG-JSON (using docker) and both 0.3.5 and latest 0.3.7 versions of g2g docker image do not contain commit in which the double quotes enclosing literal were removed from json string values (this one here https://github.com/g2glab/pg/commit/150d0e2712210b814085587fd70138c967671ab0). The commit is from May 2019 and hence it was inlcuded only in version 0.3.5 of pg. 

![image](https://user-images.githubusercontent.com/26113061/106746876-0e008f80-661b-11eb-891f-afc5efa74785.png)

Michal

**Comment by ryotayamanaka** [comment]
Hi @michalmiklas

Thank you for the great suggestion!

You are right. We should update the PG Tools on the Docker image. Let us fix and let you know!

**Comment by ryotayamanaka** [comment]
Now this should work (and the output JSON should not has the unnecessary double quotes).

```
$ alias g2g='docker run --rm -v $PWD:/work g2glab/g2g:0.3.8 g2g'
$ g2g file.g2g file.ttl -f json
```

Again, thank you very much for your feedback! @michalmiklas

**Comment by misqe** [comment]
@ryotayamanaka thank you! much appreciated.
works as expected now:
![image](https://user-images.githubusercontent.com/26113061/106769881-59c03280-6635-11eb-8f31-c91006d9d4e0.png)
