### ISSUE TITLE
GPG の拡張子は .gpg でなく .pg でよいのではないか？

### ISSUE THREAD

**Issue by ryotayamanaka** [g2gml/g2g#3]
ぐっとわかりやすくなりますね

**Comment by ryotayamanaka** [comment]
.pg にすることになりました。修正完了したら Close しましょう。

**Comment by ryotayamanaka** [comment]
拡張子は .pg としても「GPG 形式」という呼び名は「Generic」という方針がわかっていいなあと感じています。拡張子は「.pg」スクリプトは「pg_to_neo.js」みたいに「pg」にして、ドキュメント上は「GPG 形式」と表現するとかなんでしょうか？

**Comment by hchiba1** [comment]
賛成です

**Comment by ryotayamanaka** [comment]
会話した結果、拡張子は「.pg」、スクリプトも「pg_to_neo.js」みたいな感じ、ドキュメント上の呼び名は「Generic PG 形式」とすることになりました (^^
