### ISSUE TITLE
GPG の type:person は :person でいいのではないか？

### ISSUE THREAD

**Issue by ryotayamanaka** [g2gml/g2g#4]
ノード／エッジともにタイプ（Neo ではラベルだったりする）を示すプロパティの予約語「type」を用いて「type:person」と表記していますが、これを「:person」としてしまうことで予約語を使わなくて済んで、より Generic な表現になるのではないか

**Comment by ryotayamanaka** [comment]
type と label など、わかりにくい予約語なので、排除してみます。修正が完了したら Close しましょう。

**Comment by matsusho070** [comment]
コミットc4f68ceff2f838e363774eec50312d9db5fc791fで、pgからは除くようにしましたが
pg_to_neo.jsとpg_to_pgx.jsでは未対応です

**Comment by ryotayamanaka** [comment]
pg_to_neo.js と pg_to_pgx.js でも対応しましたので一度クローズします！
