### ISSUE TITLE
GPG ではノード ID の重複は許されるか？

### ISSUE THREAD

**Issue by ryotayamanaka** [g2gml/g2g#6]
GPG のノード記述では、1行に 1ノードID が記載されるが、同じノード ID が複数行に記載されることは許されるか？

```
<node_01> <prop_A>:<value_01> <prop_B>:<value_02>
<node_01> <prop_A>:<value_03> <prop_C>:<value_04>
```

特に、異なる GPG ファイルに node_01 のプロパティ情報がそれぞれ記載されいているときなど、どのように結合するかが問題となる。

**Comment by hchiba1** [comment]
いろいろなケースに対応できるように、と考えると、重複を許してもいいような気もします.
その場合もいくつか考え方があるかと思います.
i) Specificな形式(PGX等)に変換する際に、各実装で許されるものかどうかを検査して、エラー・warning等を出すべき?
ii) Specificな形式への変換は、あまり厳密にせずとりあえず機械的にやってしまって、その後の振る舞いを各実装にまかせる?（ロード時に上書きされる、warningを出す、エラーになる等）
iii) 複数行に書くのが許されない実装があるとしたら、重複した行を見つけて1行にマージしないといけなくて、入力全体を一度読み込んで変換する処理が必要になる?
(あまり各実装のことを知らずに書いていますが..)
現状で動かすと、ii)に近いということになるでしょうか.

**Comment by ryotayamanaka** [comment]
このイシューは PG のリポジトリに移動します。
https://github.com/g2gml/pg/issues/5
