### ISSUE TITLE
有向エッジと無向エッジの区別

### ISSUE THREAD

**Issue by ryotayamanaka** [g2gml/g2g#8]
エッジのマッピング定義に有向エッジと無向エッジの区別はあるか

```
(p1:Person)-[:follows]-(p2:Person)
    ?p1 :follows ?p2 .
```

例えば上記の場合、無向エッジに見えるが、実際には p1 --> p2 の有向エッジと解釈されて結果が出力されている。現状では PG 形式が有効エッジのみをサポートしているので、マッピングも有向のみとして、矢印付きの有向っぽいシンタックスにするのはいかがでしょうか？

```
(p1:Person)-[:follows]->(p2:Person)
    ?p1 :follows ?p2 .
```

**Comment by hchiba1** [comment]
賛成です.
> 矢印付きの有向っぽいシンタックスに

**Comment by matsusho070** [comment]
私も賛成です。

強いて言うならPG形式側にエッジの向きの有無の情報を持たせられる方針にすると一番G2GMLとPGの表現力は高くなる気もするのですが、グラフDBにインポートする時のことを考えると現状でやる価値はあまりなさそうですよね・・・

**Comment by ryotayamanaka** [comment]
> PG形式側にエッジの向きの有無の情報を持たせられる方針

私もこちらに惹かれはじめているのですが、まずは PG 形式が有効エッジしか持てない前提でシンタックスだけ変更しましょうか。

**Comment by hchiba1** [comment]
はい、とりあえずこちらを変更したとしても、他には影響を及ぼさなそうですね：
G2GMLのexampleの修正が多少, 煩雑でしょうか. でも今はそんなにたくさんはないですね.

**Comment by ryotayamanaka** [comment]
一度こちらは Close します。PG 形式の将来課題としてこちらのイシューに引き継ぎます。
https://github.com/g2gml/pg/issues/3
